# Generated by Django 4.1.4 on 2023-01-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='y_pos',
            field=models.IntegerField(default=0),
        ),
    ]
