# Generated by Django 4.1.4 on 2023-01-03 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_ball_y_pos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ball',
        ),
    ]
